### ISSUE TITLE
!team <color> Command

### ISSUE THREAD

**Issue by MrLotU** [UHCBot/UHCBot#8]
Command used to join a specific team, command should do the following:
1. join the team specified (using the color param)
2. print to the chat that the user joined that team
Or:
Print an error if the <color> param is non existing

**Comment by Alkali-Metal** [comment]
I am going to recommend that this info be stored in a json file of sorts, because then if the bot for some reason crashes or you stop the code to run an update, it won't clear the lists or arrays or whatever you want to call them and you can still access the data after the crash/restart.

**Comment by Alkali-Metal** [comment]
Sooo.... I'mma suggest something else seen-as-how JSON *can* be a pain, does it really matter if the players can access the voice channels before the UHC actually starts? Because if not, why not just add the colour role right when they run the `!team <colour>`. If I am mistaken let me know, because it seems to me like this would be the best way to do it without getting ***too*** complicated.

**Comment by MrLotU** [comment]
Done, will be added once #10 is merged

**Comment by MrLotU** [comment]
Finished, will be added once #10 get's merged.
